[package]
name = "api_response"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.0"
egui = "0.32.0"
reqwest = { version = "0.12.23", features = ["json"] }
serde_json = "1.0.142"
tokio = { version =  "1.47.1", features = ["full"] }
